# Generated by Django 5.1.6 on 2025-02-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('AP', 'Apartment'), ('HS', 'House'), ('CO', 'Condo'), ('TH', 'Townhouse'), ('OT', 'Other')], default='AP', help_text='Type of property', max_length=2),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1, help_text='Number of rooms in the property'),
        ),
    ]
